---
  - hosts: all
    become: true
    roles:
      - role: docker-ce
        channel: stable
    tasks:
      - name:  Add default vagrant user in docker group
        user: 
          name: vagrant
          groups: docker